AK2: backend: Some workarounds for Xiaomi Redmi 3 (ido)
Official TWRP and some other recoveries ship BusyBox NDK built-in at
/sbin/busybox. By default, AnyKernel2 backend will setup it's own
busybox and mostly ended with "Recovery busybox setup failed" error.
This patch will check if /sbin/busybox is exist and use it instead.

Tested on Official TWRP 3.1.1-0 and cofface's TWRP 3.0.2-2 modified by
opt_step and peter23 @ 4PDA (thanks to https://t.me/exterreo for testing
this on that recovery).

Signed-off-by: Albert I <krascgq@outlook.co.id>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -42,7 +42,10 @@ if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
   abort "Unzip failed. Aborting...";
 fi;
 chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
-bb=/tmp/anykernel/tools/busybox;
+test -f /sbin/busybox && bb=/sbin/busybox;
+if [ -z "$bb" ]; then
+  bb=/tmp/anykernel/tools/busybox;
+fi;
 
 ui_print "$(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
 ui_print " ";
@@ -69,13 +72,16 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
 fi;
 
 ui_print "Installing kernel...";
-for i in $($bb --list); do
-  $bb ln -s $bb /tmp/anykernel/bin/$i;
-done;
-if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
-  abort "Recovery busybox setup failed. Aborting...";
+if [ "$bb" == "/tmp/anykernel/tools/busybox" ]; then
+  for i in $($bb --list); do
+    $bb ln -s $bb /tmp/anykernel/bin/$i;
+  done;
+  if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
+    abort "Recovery busybox setup failed. Aborting...";
+  fi;
+  bb="PATH=/tmp/anykernel/bin:$PATH $bb";
 fi;
-PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
+$bb ash /tmp/anykernel/anykernel.sh $2;
 if [ $? != "0" ]; then
   abort;
 fi;
