AK2: backend: Cosmetic updates!
Signed-off-by: Albert I <krascgq@outlook.co.id>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -26,20 +26,31 @@ getprop() { test -e /sbin/getprop && /sbin/getprop $1 || file_getprop /default.p
 cleanup() { rm -rf /tmp/anykernel; }
 abort() {
   if [ ! -f /tmp/anykernel/anykernel.sh -o "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
-    ui_print "$*"; cleanup; umount /system; umount /data; exit 1;
+    ui_print "$*"; ui_print " "; cleanup; umount /system; umount /data; exit 1;
   else
-    ui_print "$*"; umount /system; umount /data; exit 1;
+    ui_print "$*"; ui_print " "; umount /system; umount /data; exit 1;
   fi;
 }
 
 show_progress 1.34 4;
+ui_print "  ____________________________________  ";
+ui_print " |    _____     _         _ _         | ";
+ui_print " |   / __\ |___| |__  __ | | |_   _   | ";
+ui_print " |  | /  |  _  \  __|/  \| | | | | |  | ";
+ui_print " |  | \__| | | | |__| :: | | | |_| |  | ";
+ui_print " |   \___/_/ |_/____/\__/|_|_|\___ |  | ";
+ui_print " |    * A KudProject Kernel *|_____|  | ";
+ui_print " |____________________________________| ";
+ui_print " |                                    | ";
+ui_print " |  AnyKernel2 by osm0sis @ xda-devs  | ";
+ui_print " |____________________________________| ";
 ui_print " ";
 cleanup;
 mkdir -p /tmp/anykernel/bin;
 cd /tmp/anykernel;
 unzip -o "$ZIPFILE";
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
-  abort "Unzip failed. Aborting...";
+  abort " ! Unzip failed. Aborting...";
 fi;
 chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
 test -f /sbin/busybox && bb=/sbin/busybox;
@@ -47,57 +58,50 @@ if [ -z "$bb" ]; then
   bb=/tmp/anykernel/tools/busybox;
 fi;
 
-ui_print "$(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
-ui_print " ";
-ui_print "AnyKernel2 by osm0sis @ xda-developers";
-ui_print " ";
 umount /system 2>/dev/null;
 mount -o ro -t auto /system;
 mount /data 2>/dev/null;
 test -f /system/system/build.prop && root=/system;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
-  ui_print "Checking device...";
+  ui_print " - Checking device...";
   for i in 1 2 3 4 5; do
     testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
     if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
-      ui_print "$testname";
+      ui_print "   $testname - Device supported.";
       match=1;
     fi;
   done;
-  ui_print " ";
   if [ "$match" != 1 ]; then
-    abort "Unsupported device. Aborting...";
+    abort " ! Unsupported device. Aborting...";
   fi;
 fi;
 
-ui_print "Installing kernel...";
+ui_print " - Installing kernel...";
 if [ "$bb" == "/tmp/anykernel/tools/busybox" ]; then
   for i in $($bb --list); do
     $bb ln -s $bb /tmp/anykernel/bin/$i;
   done;
   if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
-    abort "Recovery busybox setup failed. Aborting...";
+    abort " ! Recovery busybox setup failed. Aborting...";
   fi;
   bb="PATH=/tmp/anykernel/bin:$PATH $bb";
 fi;
 $bb ash /tmp/anykernel/anykernel.sh $2;
 if [ $? != "0" ]; then
-  abort;
+  abort " ! Installation failed. Aborting...";
 fi;
 
-ui_print " ";
-ui_print "Patching system...";
+ui_print " - Patching thermal engine...";
 mount -o rw,remount -t auto /system;
 $bb ash /tmp/anykernel/chtolly.sh $2;
 mount -o ro,remount -t auto /system;
 if [ $? != "0" ]; then
-  abort;
+  abort " ! Thermal engine patch failed. Aborting...";
 fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
-  ui_print " ";
-  ui_print "Pushing modules...";
+  ui_print " - Pushing modules...";
   mount -o rw,remount -t auto /system;
   cp -rf /tmp/anykernel/modules/* $root/system/lib/modules/;
   set_perm_recursive 0 0 0755 0644 $root/system/lib/modules;
@@ -106,17 +110,17 @@ fi;
 
 case $(basename "$ZIPFILE" .zip) in
   *-debugging)
-    ui_print " ";
-    ui_print "Creating debugging archive in zip directory...";
+    ui_print " - Creating debugging archive in zip directory...";
     $bb tar -czvf "$DIR/anykernel2-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" /tmp/*;
   ;;
 esac;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
+  ui_print " - Cleaning up residuals...";
   cleanup;
 fi;
 
 umount /system;
 umount /data;
+ui_print " - Done. Enjoy KudProject release!";
 ui_print " ";
-ui_print "Done!";
